#CVManager.py
"""
    ** Retrieve CSV file from RDBManager.
    ** Fold the csv into 10 datasets using FoldManager.py
    ** 9 folds: Training
    ** 1 fold: Testing
    ** Each fold is stored into a csv file and also saved into a DLL

    - path: this is where you will store the csv generated by GETCSV()
    - folds: the number of folds you want to fold csv into
    - row_label: the label which GETCSV will give each rows
    - column_label: the label which GETCSV will give each column_label
    - num_rows: number of rows in csv generated by GETCSV
    - num_columns: number of columns in csv generated by GETCSV
"""
import sys
sys.path.append('../')
sys.dont_write_bytecode = True

from DLL import _DLL
from FoldManager import generateFolds
from RawDB.RDBManager import GETCSV
from crossValidation import validation

def CrossValidate():
    path = '../../../data/test.csv'
    # path = '/specify/path/here'
    folds = 10
    row_label = "CANCERS"
    column_labels = "FEATURES"
    num_rows = 10
    num_columns = 7

    #GETCSV(row_label, column_labels, num_rows, num_columns, path)

    # List will hold 10 nodes where the head is Testing and the other 9 nodes are Training data
    List = generateFolds(path, folds)
    validation(List, folds)


CrossValidate()
